config/routes.rb
Rails.application.routes.draw do
  root "microposts#index"
  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations"

  }
  devise_scope :user do
    get "/users", to: "users/registrations#new"
    get "/users/password", to: "users/passwords#new"
    get "/users/sign_out" => "devise/sessions#destroy"
  end

  get "users/index", to: "users#index"
  get "users/:id", to: "users#show", as: "show_users"
  resources :microposts do
    resources :comments, only: [:create]
    resource :likes, only: %i[create destroy]
  end

  get "microposts/:id/comments", to: "microposts#show"

  namespace :api, { format: "json" } do
    resources :microposts, only: [:index, :show]
    resources :likes, only: [:index, :create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :content, presence: true, invalid_words: true, length: { maximum: 1000 }
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many  :tag_relationships, dependent: :destroy
  has_many  :tags, through: :tag_relationships

  #  todo: validationの実行
  def save_tags(savemicropost_tags)
    current_tags = tags.pluck(:name) unless tags.nil?
    old_tags = current_tags - savemicropost_tags
    new_tags = savemicropost_tags - current_tags

    old_tags.each do |old_name|
      tags.delete Tag.find_by(name: old_name)
    end

    new_tags.each do |new_name|
      micropost_tag = Tag.find_or_create_by(name: new_name)
      tags << micropost_tag if micropost_tag.save
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show tagname]
  before_action :correct_user, only: %i[edit update destroy]

  def index
    @q  = Micropost.left_joins(:likes, :user).
    select("users.name as user_name ,microposts.*, count(likes.id) as likes_count")
    .group(:id).ransack(params[:q])

    @microposts = @q.result.page(params[:page]).per(10)

    checked_anonymous?(@microposts)
    # render json: @microposts, status: 422
  end

  def new
    @micropost = current_user.microposts.build
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    tag_list = params[:micropost][:tag_ids].split(",").uniq
    if @micropost.save && @micropost.save_tags(tag_list)
      flash[:success] = "投稿が完了しました"
      redirect_to root_path
    else
      flash.now[:danger] = "投稿に失敗しました"
      render "new"
    end
  end

  def show
    @micropost = Micropost.find(params[:id])
    @comments = @micropost.comments.includes(:user)
    @comment = Comment.new
    #  debugger
  end

  def edit
    @micropost = Micropost.find(params[:id])
    @tag_list = @micropost.tags.pluck(:name).join(",")
  end

  def update
    @micropost = Micropost.find(params[:id])
    tag_list = params[:micropost][:tag_ids].split(",").uniq
    if @micropost.update(micropost_params) && @micropost.save_tags(tag_list)
      flash[:success] = "投稿が編集されました"
      redirect_to root_path
    else
      render "edit"
    end
  end

  def destroy
    @micropost = Micropost.find(params[:id])
    @user = @micropost.user
    @micropost.destroy
    flash[:success] = "投稿が削除されました"
    redirect_to show_users_path(@user)
  end

  private
    def micropost_params
      params.require(:micropost).permit(:content, :anonymous)
    end

    def correct_user
      @micropost = Micropost.find(params[:id])
      redirect_to root_path if @micropost.user_id != current_user.id && !current_user.admin?
    end

    def checked_anonymous?(microposts)
      microposts.each do |micropost|
    micropost.user_name = "匿名希望" if micropost.anonymous?
  end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
  def how_long_ago(post_time)
    time = time_ago_in_words(post_time) + "前に投稿"
    if time == "1分未満前に投稿"
      time = "少し前に投稿"
    end
    time
  end
end

app/views/microposts/edit.html.erb
<div class="container">
  <div class="text-center">
    <h1>投稿を編集する</h1>
    <%= render 'layouts/flash_messages' %>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_with(model: @micropost) do |f| %>
          <%= render 'layouts/error_messages', object: f.object %>
          <div class="form-group">
            <%= f.text_area :content, class: 'form-control',rows: "10", id:"content" %></br>
            <div id="counter" class="text-right"></div>
        </div>

        <div class="form-group">
          <%= f.label :tag_ids %>
          <%= f.text_field :tag_ids, class: "form-control", id:'tag_ids', value: @tag_list, placeholder: "タグは「,」で区切ってください" %>
        </div>
        <%= f.submit "投稿する", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/microposts/index.html.erb
<%= render 'layouts/flash_messages' %>
<%= search_form_for @q do |f| %>
  <div class="input-group mb-3">
    <%= f.search_field :content_cont,placeholder:"キーワードを入力" %>
    <%= f.search_field :tags_name_cont,placeholder:"タグを入力" %>
    <%= f.submit "検索" %>
  </div>
<% end %>
<% @microposts.each do |micropost| %>
  <div class="box">
    <p><%= link_to truncate(micropost.content,length:100),micropost %></p>
    <p class="text-right"><%= micropost.user_name %>　さん　 いいね数 : <%= micropost.likes_count %></p>
    <p class="text-right text-info"><%= how_long_ago(micropost.updated_at) %></p>
  </div>
<% end %>
<%= paginate @microposts %>

app/views/microposts/new.html.erb
<div class="container">
<div class="text-center">
<h1>新規投稿</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @micropost) do |f| %>
 <%= render 'layouts/error_messages', object: f.object %>
  <div class="form-group">
      <%= f.text_area :content, placeholder: "悩みを投稿してみましょう", class: 'form-control  content-count',id:"content",rows: "10" %></br>
        <p id="counter" class="text-right"></p>
  </div>

  <div class="form-group">
      <%= f.label :tag_ids %>
      <%= f.text_field :tag_ids, class: "form-control", id:'tag_ids', placeholder: "タグは「,」で区切ってください" %>
  </div>

  <div class="form-group">
        <%= f.label :anonymous, class: "checkbox inline" do %>
        <%= f.check_box :anonymous %>
        <span>匿名で投稿する場合は、ここにチェックを入れてください</span>
        <% end %>
  </div>
  <%= f.submit "投稿する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</div>
</div>

app/views/microposts/show.html.erb
<%= render 'layouts/flash_messages' %>
<div class="container">
  <div class="content-box">
    <%if @micropost.anonymous? %>
      <h3>匿名希望　さん</h3>
    <% else %>
      <h3><%=@micropost.user.name %>　さん</h3>
    <% end %>
    <p class="break-word"><%=safe_join(@micropost.content.split("\n"),tag(:br))%></p>
    <div>
      <% @micropost.tags.each do |tag| %>
        <%= link_to tag.name,"/microposts?q%5Btags_name_cont%5D=#{tag.name}",class:"badge bg-primary" %>
      <% end %>
    </div>
    <div class="text-right">
      <div>
        <% if user_signed_in?%>
          <div id="like">
            <like-button :user-id="<%= current_user.id %>" :micropost-id="<%= @micropost.id %>"></like-button>
          </div>
          <% if @micropost.user_id == current_user.id %>
            <%= link_to "編集する",edit_micropost_path(@micropost) %>
            <%= link_to "削除する", @micropost, method: :delete,id: 'delete_button',
                                  data: { confirm: "本当に削除しますか?" } %></br>
          <% end %>
        <% end %>
        <%= how_long_ago(@micropost.updated_at) %>
      </div>
    </div>
  </div>
  <% if user_signed_in? %>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_with(model:[@micropost, @comment], method: :post) do |f| %>
          <%= render 'layouts/error_messages', object: f.object %>
          <div class="form-group">
            <%= f.text_area :content,placeholder: "コメントしてみましょう", class: 'form-control',id:"content",rows: "10"%></br>
                    <div id="counter" class="text-right">
        </div>
        </div>
        <%= f.hidden_field :micropost_id, value: @micropost.id %>
        <div class="text-center">
          <%= f.submit "コメントする", class: "btn btn-primary" %>
        </div>
      <% end %>
    <% else %>
      <p class="text-center">コメントするにはログインしてください</p>
    <% end %>
    <h2 class="text-center">コメント一覧</h2>
    <% if @comments.length == 0%>
      <p class="text-center">コメントはまだありません</p>
    <% end %>
    <% @comments.each do |comment|%>
      <% if comment.user_id == @micropost.user_id && @micropost.anonymous? %>
        匿名希望さん
      <% else%>
        <%= comment.user.name %>
      <% end %>
      <p class="break-word"><%= comment.content %></p>
    </br>
  <% end %>
</div>